# Generated by Django 4.0.2 on 2022-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('pswd', models.CharField(max_length=25)),
            ],
        ),
    ]
