# Generated by Django 4.0.2 on 2022-03-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pstorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255, unique=True)),
                ('padd', models.CharField(max_length=255)),
                ('prate', models.IntegerField()),
                ('tslot', models.IntegerField()),
                ('aslot', models.IntegerField()),
            ],
        ),
    ]
