# Generated by Django 4.0.2 on 2022-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('contact', models.CharField(max_length=255, verbose_name='contact')),
                ('email', models.EmailField(max_length=255, verbose_name='padd')),
                ('feedback', models.CharField(max_length=255, verbose_name='feedback')),
            ],
        ),
    ]
