# Generated by Django 4.0.2 on 2022-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(verbose_name='feedback'),
        ),
    ]
