# Generated by Django 4.0.2 on 2022-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0003_alter_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='pstorey1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=25, unique=True)),
                ('avail', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='pstorey',
            field=models.EmailField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
