# Generated by Django 4.0.2 on 2022-03-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0004_pstorey1_feedback_pstorey_alter_feedback_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pstorey',
            name='aslot',
        ),
    ]
