# Generated by Django 4.0.2 on 2022-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0005_remove_pstorey_aslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='fname')),
                ('lname', models.CharField(max_length=150, verbose_name='lname')),
                ('contact', models.IntegerField(max_length=10, verbose_name='conatct')),
                ('city', models.CharField(max_length=25, verbose_name='city')),
                ('usname', models.CharField(max_length=255, unique=True, verbose_name='email')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('pswd', models.CharField(max_length=25, verbose_name='pswd')),
            ],
        ),
    ]
