# Generated by Django 4.0.2 on 2022-03-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
