# Generated by Django 4.0.2 on 2022-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='pstorey',
            field=models.CharField(max_length=255),
        ),
    ]
