# Generated by Django 4.0.2 on 2022-04-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPS', '0008_alter_feedback_pstorey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='message',
        ),
    ]
